# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FaceDetectionApp' do
    use_frameworks!
    pod 'MediaPipeTasksVision'
    pod 'OpenCV', '3.4.0'

end
